# Generated by Django 5.2 on 2025-04-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='BBL',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='building',
            name='BIN',
            field=models.CharField(default='', max_length=30),
        ),
    ]
