# Generated by Django 5.2 on 2025-04-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_building_bbl_building_bin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='service',
        ),
        migrations.AddField(
            model_name='building',
            name='services',
            field=models.ManyToManyField(to='db.service'),
        ),
    ]
