# Generated by Django 5.2 on 2025-04-22 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_rename_customer_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='building',
            name='BBL',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='building',
            name='BIN',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='building',
            name='adjusted_gfa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='basement_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='building',
            name='bis_bbl_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='bis_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.client'),
        ),
        migrations.AlterField(
            model_name='building',
            name='number_of_bins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='number_of_floors',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='uniformly_adjusted_gfa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='zola_gfa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='zola_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='attestation_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='attestations/'),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='attestation_received',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='building',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.building'),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='cbl_ll97_path_2025',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='dob_filing_fee_paid',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='dob_now_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='dob_now_transaction_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='dob_pmt_confirmation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='espm_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='field_schedule',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='invoice_sent',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='ll87_filed',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='ll87_needed_2025',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='ll88_lighting',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='ll88_needed',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='ll88_submeter',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='ll97_schedule',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='proof_of_correction',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='proof_of_correction_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='proof_sent',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='request_info_date',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='buildingcompliance',
            name='request_share_espm',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
