# Generated by Django 5.2 on 2025-04-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_remove_client_first_name_remove_client_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='adjusted_gfa',
        ),
        migrations.RemoveField(
            model_name='building',
            name='basement_code',
        ),
        migrations.RemoveField(
            model_name='building',
            name='bis_bbl_link',
        ),
        migrations.RemoveField(
            model_name='building',
            name='bis_link',
        ),
        migrations.RemoveField(
            model_name='building',
            name='number_of_floors',
        ),
        migrations.RemoveField(
            model_name='building',
            name='uniformly_adjusted_gfa',
        ),
        migrations.RemoveField(
            model_name='building',
            name='zola_gfa',
        ),
        migrations.RemoveField(
            model_name='building',
            name='zola_link',
        ),
        migrations.AddField(
            model_name='building',
            name='borough',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_info',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='service_tracking_info',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.DeleteModel(
            name='BuildingCompliance',
        ),
    ]
