# Generated by Django 5.2 on 2025-04-24 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_remove_building_adjusted_gfa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_tracking_info',
        ),
        migrations.AlterField(
            model_name='building',
            name='BBL',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='building',
            name='BIN',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='building',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.client'),
        ),
        migrations.AlterField(
            model_name='building',
            name='services',
            field=models.ManyToManyField(related_name='buildings', to='db.service'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='BuildingTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_info', models.CharField(default='Unknown', max_length=500)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='db.building')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='db.service')),
            ],
            options={
                'indexes': [models.Index(fields=['building'], name='db_building_buildin_935489_idx'), models.Index(fields=['service'], name='db_building_service_69e4fb_idx')],
                'unique_together': {('building', 'service')},
            },
        ),
    ]
