# Generated by Django 5.2 on 2025-04-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_remove_client_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_info',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
