# Generated by Django 5.2 on 2025-04-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_client_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingtracking',
            name='LL84_2020_Filed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buildingtracking',
            name='LL84_2021PMT',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='buildingtracking',
            name='LL84_2022_Score_to_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buildingtracking',
            name='LL84_2023_Invoice_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buildingtracking',
            name='LL84_2023_PMT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buildingtracking',
            name='LL84_2024_PMT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buildingtracking',
            name='LL84_2024_Score',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='buildingtracking',
            name='LL84_2025_Paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buildingtracking',
            name='LL84_2025_submission',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='buildingtracking',
            name='LL84_23_Grading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buildingtracking',
            name='LL84_24_Outreach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buildingtracking',
            name='LL84_24_Submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buildingtracking',
            name='LL84_Confirmation_Email',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='buildingtracking',
            name='LL84_Price',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='buildingtracking',
            name='LL84_Show_data_in_BEAM',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='buildingtracking',
            name='LL84_Submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buildingtracking',
            name='LL84_water_benchmark',
            field=models.BooleanField(default=False),
        ),
    ]
